FROM node:10-alpine

RUN apk --update --no-cache add curl bash build-base python3 docker zip git && \
  pip3 install --upgrade pip && \
  pip --no-cache-dir install awscli --upgrade && \
  npm install --global npm@latest

# update apk repo
RUN echo "http://dl-4.alpinelinux.org/alpine/v3.9/main" >> /etc/apk/repositories && \
    echo "http://dl-4.alpinelinux.org/alpine/v3.9/community" >> /etc/apk/repositories

# install chromedriver
RUN apk update
RUN apk update && apk add chromium chromium-chromedriver

RUN apk add --update nodejs npm

RUN npm install -g lighthouse

ARG debug
ENV DEBUG=$debug

RUN mkdir /junit
RUN mkdir /selenium
RUN mkdir /selenium/html-reports

COPY requirments.txt /selenium/requirments.txt
WORKDIR /selenium
RUN pip install -r requirments.txt
COPY import_pages.py /selenium/import_pages.py
COPY appium_selenium_driver /selenium/appium_selenium_driver
COPY lighthouse_tools /selenium/lighthouse_tools
COPY pages /selenium/pages
COPY tests /selenium/tests