FROM python:3.6
ENV PYTHONUNBUFFERED 1
ENV RUNNING_ON_DOCKER True

ARG debug
ENV DEBUG=$debug

RUN mkdir /junit
RUN mkdir /selenium
RUN mkdir /selenium/logs-dir

COPY requirements.txt /selenium/requirements.txt
WORKDIR /selenium
RUN pip install -r requirements.txt
COPY import_pages.py /selenium/import_pages.py
COPY appium_selenium_driver /selenium/appium_selenium_driver
COPY pages /selenium/pages
COPY tests /selenium/tests