version: "3"
services:
  python-tests:
    ipc: "host"
    build:
      context: ../
#      args:
#        SITE_URL: ${SITE_URL}
#        ALERT_THRESHOLD: ${ALERT_THRESHOLD}
#        ATTACK_STRENGTH: ${ATTACK_STRENGTH}
#        REMOTE: true

      dockerfile: ./docker/Dockerfile-python-selenium-remote
    environment:
     - WORKSPACE=/selenium
     - SITE_URL=${SITE_URL}
     - ALERT_THRESHOLD=${ALERT_THRESHOLD}
     - ATTACK_STRENGTH=${ATTACK_STRENGTH}
     - ZAP_IP=${ZAP_IP}

#     - ZAP_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' zap)"
    depends_on:
      - selenium-server
    ports:
      - 5555:5555
    volumes:
      - "${PWD}/zap_reports:/selenium/reports:rw"
    container_name: python-tests
    command: >
      bash -c "sleep 10 && python -m pytest -sv tests/ --junitxml=/junit/result.xml"

  selenium-server:
    image: selenium/standalone-chrome
    container_name: selenium-server
    depends_on:
      - zap
    ports:
      - 4444:4444
    environment:
      - http_proxy=${ZAP_IP}:8081
      - https_proxy=${ZAP_IP}:8081
    volumes:
      - /dev/shm:/dev/shm

  